### ISSUE TITLE
new Random vs random.clone

### ISSUE THREAD

**Issue by Badestrand** [transitive-bullshit/random#52] opened 2023-02-26 06:20 UTC
Hi!

First, thanks for this super cool library.

I just ran into an issue which may just be an issue of the documentation.

When working with seeds, I expected `new Random(seedrandom('tinykittens'))` to work the same as `random.use(seedrandom('tinykittens'))` or `random.clone(seedrandom('tinykittens'))`.

But appearently `new Random` doesn't seed correctly?
```js
console.log('rng test random..')
for (let i=0; i<3; ++i) {
	const prng = new Random(seedrandom('my-seed'))
	console.log(prng.float())
}
// =>
// 0.6724578711199012
// 0.014330871501025522
// 0.16677254682291287
```

If this is expected behaviour then I think the documentation should be adjusted near the text `You can also instantiate a fresh instance of Random`.

**Comment by transitive-bullshit** [comment] 2023-02-26 22:18
@Badestrand this definitely looks like a bug and is unintended behavior.

Thanks for reporting it 🙏

**Comment by lespin** [comment] 2023-07-22 17:22
Same problem here. Could you tell if this module is maintained ?

**Comment by transitive-bullshit** [comment] 2024-09-03 03:01
This should now be fixed in https://github.com/transitive-bullshit/random/releases/tag/v5.0.0

I added unit tests for this case to ensure it doesn't regress.

**Closed by transitive-bullshit** 2024-09-03 03:01 UTC
